sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - docker build -t cryptocard .

script:
  - docker run cryptocard gradle check --info --user 0
  - docker run cryptocard gradle test --info --user 0

notifications:
  email: false