sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - docker build -t half2me/cryptocard .

script:
  - docker run cryptocard gradle check --info
  - docker run cryptocard gradle test --info

notifications:
  email: false