sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker


before_install:
  - docker run -d gradle:4.5.1-jdk8
  - docker ps -a

script:
  - sh "echo not much yet"

notifications:
  email: false