sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
  - docker build -t cryptocard .

script:
  - docker run cryptocard gradle check --info
  - docker run cryptocard gradle buildJavaCard --info

notifications:
  email: false